name: Build with Emscripten and CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: set up cache for emscripten
      uses: actions/cache@v3
      id: cache-emsdk
      with:
        path: emsdk
        key: emscripten-${{ runner.os }}-latest
        restore-keys: |
          emscripten-${{ runner.os }}-

    - name: set up emscripten environment
      if: steps.cache-emsdk.outputs.cache-hit != 'true'
      run: |
        if [ ! -d "emsdk" ]; then
        git clone https://github.com/emscripten-core/emsdk.git
        fi
        cd emsdk
        ./emsdk install 3.1.74
        ./emsdk activate 3.1.74
        source ./emsdk_env.sh
        cd ..

    - name: Clone/Update SDL
      run: |
        git clone https://github.com/klukaszek/SDL.git
        cd SDL
        git pull origin emscripten-webgpu
        git submodule update --init

    - name: Build SDL
      run: |
        source emsdk/emsdk_env.sh
        mkdir -p SDL_Build
        cd SDL_Build
        emcmake cmake ../SDL -DSDL_WEBGPU=ON -DSDL_RENDER_WEBGPU=ON -GNinja    
        ninja

    - name: Build project
      run: |
        # Activate Emscripten environment
        source emsdk/emsdk_env.sh
        mkdir -p build
        cd build
        git submodule update --init
        emcmake cmake .. -DSDL3_DIR="./SDL_Build/" -GNinja
        ninja
        mv SDL_gpu_examples.html index.html

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/
